# Generated by Django 3.1.4 on 2020-12-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=140)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(upload_to='images')),
            ],
        ),
    ]
