# Generated by Django 3.1.4 on 2020-12-03 03:19

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
