# Generated by Django 3.1.4 on 2020-12-04 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_profile_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
